packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@changesets/cli': ^2.27.10
  '@platforma-sdk/block-tools': ^2.5.0
  '@platforma-sdk/model': ^1.20.0
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/test': ^1.20.3
  '@platforma-sdk/ui-vue': ^1.20.5
  '@platforma-sdk/workflow-tengo': ^2.8.1
  '@types/lodash': ^4.17.13
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  'lodash': ^4.17.21
  'tsup': ^8.3.5
  'turbo': ^2.3.3
  'typescript': ~5.6.3
  'vite': ^6.0.3
  'vitest': ^2.1.8
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.8.8
  '@platforma-open/milaboratories.samples-and-data.model': ^1.8.2
  '@platforma-open/milaboratories.mixcr-clonotyping': ^1.6.0
  '@platforma-open/milaboratories.mixcr-clonotyping.model': ^1.4.2
