packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@changesets/cli': ^2.28.0
  '@platforma-sdk/block-tools': ^2.5.25
  '@platforma-sdk/model': ^1.24.9
  '@platforma-sdk/tengo-builder': ^2.0.1
  '@platforma-sdk/test': ^1.24.9
  '@platforma-sdk/ui-vue': ^1.24.9
  '@platforma-sdk/workflow-tengo': ^3.0.3
  '@types/lodash': ^4.17.15
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.7.0
  'lodash': ^4.17.21
  'tsup': ^8.3.6
  'turbo': ^2.4.4
  'typescript': ^5.7.3
  'vite': ^6.2.2
  'vitest': ^3.0.8
  'vue': ^3.5.13
  'vue-tsc': ^2.2.2

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.9.8
  '@platforma-open/milaboratories.samples-and-data.model': ^1.9.1
  '@platforma-open/milaboratories.mixcr-clonotyping': ^1.8.14
  '@platforma-open/milaboratories.mixcr-clonotyping.model': ^1.8.0
