packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@changesets/cli': ^2.28.1
  '@platforma-sdk/block-tools': ^2.5.30
  '@platforma-sdk/model': ^1.26.0
  '@platforma-sdk/tengo-builder': ^2.0.2
  '@platforma-sdk/test': ^1.27.4
  '@platforma-sdk/ui-vue': ^1.27.5
  '@platforma-sdk/workflow-tengo': ^3.2.1
  '@types/lodash': ^4.17.16
  '@vitejs/plugin-vue': ^5.2.3
  '@vueuse/core': ^13.0.0
  'lodash': ^4.17.21
  'tsup': ^8.4.0
  'turbo': ^2.4.4
  'typescript': ^5.8.2
  'vite': ^6.2.5
  'vitest': ^2.1.8
  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.3
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
  '@platforma-open/milaboratories.mixcr-clonotyping': ^1.8.24
  '@platforma-open/milaboratories.mixcr-clonotyping.model': ^1.9.0
