packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@changesets/cli': ^2.27.10
  '@platforma-sdk/block-tools': ^2.3.25
  '@platforma-sdk/model': ^1.13.0
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/test': ^1.10.12
  '@platforma-sdk/ui-vue': ^1.13.0
  '@platforma-sdk/workflow-tengo': ^2.3.0
  '@types/lodash': ^4.17.13
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^11.3.0
  'lodash': ^4.17.21
  'tsup': ^8.3.5
  'typescript': ~5.6.3
  'vite': ^6.0.0
  'vitest': ^2.1.6
  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.7.1
  '@platforma-open/milaboratories.samples-and-data.model': ^1.7.1
  '@platforma-open/milaboratories.mixcr-clonotyping': ^1.4.2
  '@platforma-open/milaboratories.mixcr-clonotyping.model': ^1.3.2
